vich_uploader:
    db_driver: orm
    mappings:
        consoles_images:
            uri_prefix: img/uploads/consoles
            upload_destination: '%kernel.project_dir%/public/img/uploads/consoles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
