# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    app.licenses_service:
        class : App\Service\LicensesService
        arguments : [
            - App\Repository\LicenseRepository
        ]

    app.items_service:
        class : App\Service\ItemsService
        arguments : [
            - App\Repository\ItemRepository
        ]

    app.games_service:
        class : App\Service\GamesService
        arguments : [
            - App\Repository\GameRepository
        ]

    app.consoles_service:
        class : App\Service\ConsolesService
        arguments : [
            - App\Repository\ConsoleRepository
        ]

    app.characters_service:
        class : App\Service\CharactersService
        arguments : [
            - App\Repository\CharacterRepository
        ]

    app.genres_service:
        class : App\Service\GenresService
        arguments : [
            - App\Repository\GenreRepository
        ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
